[package]
name = "vorpal"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.219"

[[bin]]
name = "jubjub"
path = "src/jubjub.rs"

[dev-dependencies]
serde = { version = "1.0.219", features = ["derive"] }
